apiVersion: v1
kind: Service
metadata:
  name: nebulaops-service
spec:
  type: NodePort
  selector:
    app: nebulaops-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30080

